
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# used to convert MD files into html files
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - *.md
